server:
  port: 8081
spring:
  application:
    name: customer-service
  profiles:
    include: database, kafka, eureka, redis
    active: dev
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/user
