server:
  port: 8081
spring:
  application:
    name: customer-service
  profiles:
    include: database, kafka, eureka
    active: dev
security:
  oauth2:
    resource:
      userInfoUri: http://127.0.0.1:8080/user
