spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:saleshistory
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update