server:
  port: 8083
spring:
  application:
    name: saleshistory-service
  profiles:
    include: database, kafka, eureka
    active: dev
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/user
