server:
  port: 8085
spring:
  application:
    name: customer-history-service
  profiles:
    include: kafka, redis, eureka

security:
  oauth2:
    resource:
      userInfoUri: http://One234gift-userservice:8080/user