server:
  port: 8085
spring:
  application:
    name: customer-history-service
  profiles:
    include: kafka, redis, eureka

security:
  oauth2:
    resource:
      userInfoUri: http://10.202.48.134:8080/user
