server:
  port: 8082
spring:
  application:
    name: order-service
  profiles:
    include: database, eureka, kafka, service-url
    active: dev
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/user