server:
  port: 8082
spring:
  application:
    name: order-service
  profiles:
    include: database, eureka, feign, kafka
    active: dev
security:
  oauth2:
    resource:
      userInfoUri: http://127.0.0.1:8080/user