server:
  port: 8761
spring:
  application:
    name: discover-service
  security:
    user:
      name: one234gift
      password: 1234
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
