server:
  port: 8000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://127.0.0.1:8081/
          predicates:
            - Path=/first-service/**
        - id: second-service
          uri: http://127.0.0.1:8082/
          predicates:
            - Path=/second-service/**

